name: pokedex
description: Pokedex

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.1

environment:
  sdk: '>=2.12.0 <3.3.2'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  http: ^0.13.3
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  mobx_codegen: ^2.0.2
  cached_network_image: ^3.1.0
  get_it: ^7.1.3
  lottie: ^1.1.0
  sliding_up_panel: ^2.0.0+1
  font_awesome_flutter: ^10.1.0
  bot_toast: ^4.0.1
  just_audio: ^0.9.29
  audio_video_progress_bar: ^0.10.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.0+1
  shared_preferences: ^2.0.7
  infinite_scroll_pagination: ^3.1.0
  dio: ^4.0.0
  animated_theme_switcher: ^2.0.6
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  

dev_dependencies:
  mockito:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/pokemons_types/
    - assets/images/technical_records_types/
    - assets/images/technical_machines_types/
    - assets/images/pokemons_generations/generation_1/
    - assets/images/pokemons_generations/generation_2/
    - assets/images/pokemons_generations/generation_3/
    - assets/images/pokemons_generations/generation_4/
    - assets/images/pokemons_generations/generation_5/
    - assets/images/pokemons_generations/generation_6/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_8/
    - assets/lotties/

  fonts:
    - family: CircularStd-Book
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/app_icon.png"

flutter_native_splash:
  image: "assets/images/splash_logo.png"
  color: "#FFFFFF"