name: pokedex
description: Pokedex

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  http: ^0.13.3
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  mobx_codegen: ^2.0.2
  cached_network_image: ^3.1.0
  get_it: ^7.1.3
  lottie: ^1.1.0
  sliding_up_panel: ^2.0.0+1
  font_awesome_flutter: ^9.1.0
  bot_toast: ^4.0.1
  just_audio: ^0.9.10
  audio_video_progress_bar: ^0.9.0
  flutter_launcher_icons: ^0.9.2
  

dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/pokemons_types/
    - assets/images/technical_records_types/
    - assets/images/technical_machines_types/
    - assets/images/pokemons_generations/generation_1/
    - assets/images/pokemons_generations/generation_2/
    - assets/images/pokemons_generations/generation_3/
    - assets/images/pokemons_generations/generation_4/
    - assets/images/pokemons_generations/generation_5/
    - assets/images/pokemons_generations/generation_6/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_8/
    - assets/lotties/

  fonts:
    - family: CircularStd-Book
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"